ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('djadmin/', admin.site.urls),
    path('', include('store.urls')),
    path('admin', include('store_admin.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_admin/urls.py
from . import views
from django.urls import path
urlpatterns = [            
    path('',views.admin_signin, name='admin_signin'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('signout',views.signout, name='signout'),
    path('products',views.products, name='products'),
    path('accounts',views.accounts, name='accounts'),
    path('filters',views.filters, name='filters'),
    path('edit_filters',views.edit_filters, name='edit_filters'),
    path('edit_category',views.edit_category, name='edit_category'),
    path('edit_size',views.edit_size, name='edit_size'),
    path('edit_color',views.edit_color, name='edit_color'),
    path('order_manage',views.order_manage, name='order_manage'),
    path('cancel_order_admin',views.cancel_order_admin, name='cancel_order_admin'),
    path('confirm_order_admin',views.confirm_order_admin, name='confirm_order_admin'),
    path('deliver_order_admin',views.deliver_order_admin, name='deliver_order_admin'),
    path('ship_order_admin',views.ship_order_admin, name='ship_order_admin'),
    path('refund_order',views.refund_order, name='refund_order'),
    path('customer_order/<int:id>',views.customer_order, name='customer_order'),
    path('get_data',views.get_data, name='get_data'),
    path('report',views.report, name='report'),
    path('daily_report',views.daily_report, name='daily_report'),
    path('monthly_report/<str:month>',views.monthly_report, name='monthly_report'),
    path('yearly_report/<str:year>',views.yearly_report, name='yearly_report'),
    path('filter_report/<str:from_date>/<str:to_date>',views.filter_report, name='filter_report'),
    path('download_report/<str:from_date>/<str:to_date>',views.download_report, name='download_report'),
    path('download_report_csv/<str:from_date>/<str:to_date>',views.download_report_csv, name='download_report_csv'),
    path('offer',views.offer, name='offer'),
    path('set_coupon',views.set_coupon, name='set_coupon'),
    path('set_category_offer',views.set_category_offer, name='set_category_offer'),
    path('set_product_offer',views.set_product_offer, name='set_product_offer'),
    path('cancel_offer',views.cancel_offer, name='cancel_offer'),
    path('monthly_order_report/<str:month>',views.monthly_order_report, name='monthly_order_report'),
]

store/models.py
import pytz
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User
from django.core import validators



class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True, validators=[validators.validate_email])
    mobile = models.CharField(max_length=13,null=True)
    password = models.CharField(max_length=200, null=True)
    active = models.BooleanField(default=True)
    

    
    def __str__(self):
        return self.name
    @property
    def wishlist(self):
        wish = self.wishlist_set.all()
        return wish


class Size(models.Model):
    size_choice = {
        ('XL','XL'), ('L','L'),('M','M'),('S','S')
    }
    value = models.CharField(max_length=100,choices=size_choice,default='M', null=True)
    
    def __str__(self):
        return self.value

 
    
class Color(models.Model):
    value = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.value
 
 
 
    
class Tags(models.Model):
    name = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.name   
    
 
   
class Category(models.Model):
    name = models.CharField(max_length=50, null=True)
    subcategory = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    
    
class Products(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank = True)
    description = models.CharField(max_length=250, null=True, blank=True)  
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, blank = True, null = True)
    tags = models.ForeignKey(Tags, on_delete = models.SET_NULL, blank = True, null = True)
    price = models.FloatField()
    cost = models.FloatField( null=True, blank=True)
    stock = models.IntegerField()
    date_entry = models.DateTimeField(auto_now_add = True )
    image = models.ImageField(null=True, blank=True, upload_to='')
    image2 = models.ImageField(null=True, blank=True, upload_to='')
    image3 = models.ImageField(null=True, blank=True, upload_to='')
    
    def __str__(self):
        return self.name
    
    @staticmethod
    def get_all_product():
        return Products.objects.all()
    
    @staticmethod
    def get_all_product_by_id(category_id):
        if category_id:
            return Products.objects.filter(category = category_id)
        else:
            return Products.get_all_product()
      
    
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except Exception:
            url = ''
        return url
    


class ProductVariation(models.Model):
    product = models.ForeignKey(Products, on_delete = models.CASCADE, blank = True, null = True) 
    color = models.ForeignKey(Color, on_delete = models.CASCADE, blank = True, null = True)   
    size = models.ForeignKey(Size, on_delete = models.CASCADE, blank = True, null = True) 
    
    @staticmethod   
    def get_all_product_by_color(color_id):
        if color_id:
            variations = ProductVariation.objects.filter(color = color_id).distinct('product')
            products = []
            for product in variations:
                products.append(product.product)
            return products
        else:
            return Products.get_all_product()
        
    @staticmethod   
    def get_all_product_by_size(size_id):
        if size_id:
            variations = ProductVariation.objects.filter(size = size_id).distinct('product')
            products = []
            for product in variations:
                products.append(product.product)
            return products
        else:
            return Products.get_all_product()
     
class Coupon(models.Model):
    offer_choice = {
        ('FLAT','FLAT'), ('PERCENTAGE','PERCENTAGE')
    }
    name = models.CharField(max_length=100, null=True, blank=True)
    coupon_code = models.CharField(max_length=50)
    is_expired = models.BooleanField(default=False)
    discount = models.IntegerField()
    discount_type = models.CharField(max_length=100,choices=offer_choice,default='FLAT', null=True, blank=True)
    minimum_amount = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    validity = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return self.name  
    




class CategoryOffer(models.Model):
    
    offer_choice = {
        ('FLAT','FLAT'), ('PERCENTAGE','PERCENTAGE')
    }
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, blank = True, null = True)
    is_expired = models.BooleanField(default=False)
    discount = models.IntegerField()
    minimum_amount = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    validity = models.DateField(null=True, blank=True)
    discount_type = models.CharField(max_length=100,choices=offer_choice,default='FLAT', null=True, blank=True)
    
    # def __str__(self):
    #     return self.category.name  
    

class ProductOffer(models.Model):
    
    offer_choice = {
        ('FLAT','FLAT'), ('PERCENTAGE','PERCENTAGE')
    }
    product = models.ForeignKey(Products, on_delete = models.SET_NULL, blank = True, null = True)
    is_expired = models.BooleanField(default=False)
    discount = models.IntegerField()
    minimum_amount = models.IntegerField(null=True,blank=True)
    date = models.DateField(auto_now_add=True)
    validity = models.DateField(null=True, blank=True)
    discount_type = models.CharField(max_length=100,choices=offer_choice,default='FLAT', null=True, blank=True)
        
        

class Offer(models.Model):
    coupon_offer = models.ForeignKey(Coupon, on_delete = models.SET_NULL, blank = True, null = True)
    category_offer = models.ForeignKey(CategoryOffer, on_delete = models.SET_NULL, blank = True, null = True)
    product_offer = models.ForeignKey(ProductOffer, on_delete = models.SET_NULL, blank = True, null = True)
    

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.SET_NULL, blank = True, null = True) 
    product = models.ForeignKey(Products, on_delete = models.SET_NULL, blank = True, null = True)
    quantity = models.IntegerField(default = 0, null = True, blank = True)
    
    def __str__(self):
        return str(self.id)
    


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.SET_NULL, blank = True, null = True) 
    fname = models.CharField(max_length=20, null=False, blank=False)
    lname =models.CharField(max_length=20, null=True)
    phone =models.CharField(max_length=10, null=False, blank=False)
    email =models.EmailField(max_length=30, null=False, blank=False)
    pincode = models.CharField(max_length=6, null=False, blank=False)
    state = models.CharField(max_length=20, null=False, blank=False)
    address1 = models.CharField(max_length=150, null=False, blank=False)
    address2 = models.CharField(max_length=150, null=True)
    date = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.fname   
 

      
class OrderCart(models.Model):
    status_choices={
        ('pending','pending'),('accepted','accepted'),('canceled','canceled'),('return','return'),('shipped','shipped'),('delivered','delivered'),('refunded','refunded')
    }
    customer = models.CharField(max_length=100, null=True, blank=True)
    product = models.ForeignKey(Products, on_delete = models.SET_NULL, blank = True, null = True)
    quantity = models.IntegerField(default = 0, null = True, blank = True)  
    customer_order_status = models.CharField(max_length=200, choices=status_choices, default='pending')
    coupon = models.ForeignKey(Coupon, on_delete= models.SET_NULL, blank=True, null=True)
    cart_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.product.name  
  
  
class Order(models.Model):
    status_choices={
        ('pending','pending'),('accepted','accepted'),('canceled','canceled'),('return','return'),('shipped','shipped'),('delivered','delivered')
    }
    p_status={
        ('success','success'),('failed','failed'),('pending','pending'),('refunded','refunded')
    }
    
    customer = models.ForeignKey(Customer, on_delete = models.SET_NULL, blank = True, null = True)
    guest_user= models.CharField(max_length=200, null=True, blank=True)
    shipping_address = models.ForeignKey(ShippingAddress, on_delete = models.CASCADE, blank = True, null = True)
    items = models.ForeignKey(OrderCart, on_delete = models.CASCADE, blank = True, null = True)  
    order_price = models.IntegerField(blank=True, null=True)
    discount_type = models.CharField(max_length=100, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add = True)
    delivery_date = models.DateTimeField(null=True,blank=True)
    payment_method = models.CharField(max_length=200, null=True)
    order_status = models.CharField(max_length=200, choices=status_choices, default='pending')
    razorpay_payment_id = models.CharField(max_length=100, null=True, blank=True)
    razorpay_order_id = models.CharField(max_length=100, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=100, null=True, blank=True)
    paypal_id =  models.CharField(max_length=100, null=True, blank=True)
    payment_status = models.CharField(max_length=200, choices=p_status, default='pending')
    return_reason = models.CharField(max_length=200, null=True, blank=True)
    return_order = models.BooleanField(default=False)
    
    
    def __str__(self):
        return str(self.id)
    @property
    def returnOrder(self):
        utc=pytz.UTC
        today = utc.localize(datetime.now())

store_admin/models.py
from django.db import models

# Create your models here.

store_admin/forms.py
from django import forms
from django.forms import ModelForm
from store.models import CategoryOffer, Coupon, ProductOffer

class CouponOfferForm(ModelForm):
    class Meta:
        model = Coupon
        fields =( "name","coupon_code", "is_expired","discount","minimum_amount","validity", "discount_type")
       
        widgets = {
            'name':  forms.TextInput( attrs={ 'class':"form-control", 'id':"coupon_name", 'placeholder':'Name', 'style':'background-color:white; color:black'}),
            'coupon_code':  forms.TextInput( attrs={ 'class':"form-control", 'id':"coupon_code", 'placeholder':'Coupon Code', 'style':'background-color:white; color:black'}),
            'is_expired':  forms.CheckboxInput( attrs={ 'class':"form-control", 'id':"coupon_status",'value':'1'}),
            'discount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"coupon_discount", 'placeholder':'Discount amount', 'style':'background-color:white; color:black'}),
            'minimum_amount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"coupon_minimum_amount", 'placeholder':'Minimum Value Required', 'style':'background-color:white; color:black'}), 
            'validity':  forms.DateInput( attrs={ 'type':'date','class':"form-control", 'id':"coupon_validity",  'style':'background-color:white; color:black'}), 
            'discount_type':  forms.Select( attrs={ 'class':"form-control custom-select", 'id':"coupon_discount_type", 'style':'background-color:white; color:black'}),
        }
        
        
class CategoryOfferForm(ModelForm):
    class Meta:
        model = CategoryOffer
        fields =( "category","discount","minimum_amount","validity","discount_type")
    
        widgets = {
            'category':  forms.Select( attrs={ 'class':"form-control custom-select", 'id':"category_name", 'style':'background-color:white; color:black'}),
            'discount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"category_discount", 'placeholder':'Discount amount', 'style':'background-color:white; color:black'}),
            'minimum_amount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"category_minimum_amount", 'placeholder':'Minimum Value Required', 'style':'background-color:white; color:black'}),  
            'validity':  forms.DateInput( attrs={ 'type':'date','class':"form-control", 'id':"category_validity",  'style':'background-color:white; color:black'}),
            'discount_type':  forms.Select( attrs={ 'class':"form-control custom-select", 'id':"category_discount_type", 'style':'background-color:white; color:black'}),
        }
        
        
class ProductOfferForm(ModelForm):
    class Meta:
        model = ProductOffer
        fields =( "product","discount","minimum_amount","validity","discount_type")
        
        widgets = {
            'product':  forms.Select( attrs={ 'class':"form-control custom-select", 'id':"product_name", 'style':'background-color:white; color:black'}),
            'discount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"product_discount", 'placeholder':'Discount amount', 'style':'background-color:white; color:black'}),
            'minimum_amount':  forms.TextInput( attrs={ 'class':"form-control", 'id':"product_minimum_amount", 'placeholder':'Minimum Value Required', 'style':'background-color:white; color:black'}),  
            'validity':  forms.DateInput( attrs={ 'type':'date','class':"form-control", 'id':"product_validity",  'style':'background-color:white; color:black'}),
            'discount_type':  forms.Select( attrs={ 'class':"form-control custom-select", 'id':"product_discount_type", 'style':'background-color:white; color:black'}),
        }
        
        

templates/store_admin/accounts.html
{%extends 'store_admin/admin_base.html'%}
{%load static%}
{%block content%}
        <div class="container mt-5">
          <div class="row tm-content-row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 tm-block-col">
              <div class="tm-bg-primary-dark tm-block tm-block-products">
                <div class="tm-product-table-container">
                  <table class="table table-hover tm-table-small tm-product-table">
                    <thead>
                      <tr>
                        <th scope="col">&nbsp;</th>
                        <th scope="col"> NAME</th>
                        <th scope="col">EMAIL</th>
                        <th scope="col">MOBILE</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col">&nbsp;</th>
                      </tr>
                    </thead>
                    <tbody>
                      
                      <form action="{% url 'accounts' %}" method="POST">{% csrf_token %} 
                      {%for user in users%}
                      <tr>
                        <th scope="row"></th>
                        <td class="tm-product-name">{{user.name}}</td>
                        <td>{{user.email}}</td>
                        <td>{{user.mobile}}</td>
                        {% if  user.active %}<td> <button class="btn btn-danger btn-block text-uppercase" value="{{user.id}}" type="submit" name="user_id"> Block </button> </td> 
                        {% else %}<td> <button class="btn btn-success btn-block text-uppercase" value="{{user.id}}" type="submit" name="user_id"> Unblock </button> </td>
                        {% endif %} 
                      {%endfor%}
                    </form> 
                    </tbody>
                  </table>
                </div>         
              </div>   
            </div>     
          </div>        
        </div>        
{%endblock%}    

templates/store_admin/add-product.html
{%extends 'store_admin/admin_base.html'%}
{%load static%}
{%block content%}
    <div class="container tm-mt-big tm-mb-big">
      
      {% if error %}
      <h3 style="color: red;">{{ error }}</h3>
      {% endif %}
      <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Add Product</h2>
              </div>
            </div>
            <div class="row tm-edit-product-row">
              <div class="col-xl-12 col-lg-12 col-md-12">
                <form action="{%url 'add_product'%}" class="tm-edit-product-form" method="post" enctype="multipart/form-data">
                  {%csrf_token%}
                  <div class="form-group mb-3 ">
                    <label
                      for="name"
                      >Product Name
                    </label>
                    <input id="name" name="name" type="text" class="form-control validate" required/>
                  </div>
                  <div class="form-group mb-3 ">
                    <label
                      for="description"
                      >Description</label
                    >
                    <textarea
                      class="form-control validate"
                      rows="3"
                      name="description"
                    ></textarea>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="category"
                      >Category</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="category"
                      name="category"
                      required
                    >
                      <option selected>Select category</option>
                      {%for category in categorys%}
                      <option value="{{category}}">{{category}} </option>
                      {%endfor%}
                    </select>
                  </div>
                  
                  <div class="form-group mb-3">
                    <label for="size">Size</label>
                    {%for size in sizes%}
                      <input type="checkbox" name="size" value="{{size.id}}">{{size}} 
                    {%endfor%}
                  </div>
                  <div class="form-group mb-3">
                    <label for="color">Color</label>
                      {%for color in colors%}
                      <input name="color" type="checkbox" value="{{color.id}}">{{color}}
                      {%endfor%}
                  </div>
                  <div class="row">
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="stock"
                            >Units In Stock
                          </label>
                          <input
                            required
                            min="1"
                            id="stock"
                            name="stock"
                            type="number"
                            class="form-control validate"                            
                          />
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="cost"
                            >Cost
                          </label>
                          <input
                            min="1"
                            id="cost"
                            name="cost"
                            type="number"
                            class="form-control validate"
                            required                            
                          />
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-12">
                          <label
                            for="price"
                            >Price
                          </label>
                          <input
                            min="1"
                            id="price"
                            name="price"
                            type="number"
                            class="form-control validate"
                            required                            
                          />
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-6 d-inline">
                          <div class="">
                            <label for="productimage" class=""> Image </label>
                    
                            <input
                              type="file"
                              required
                              id="id_image1"
                              name="image"
                              accept="image/*"
                              class="form-control"
                              onchange="viewImage1(event)"
                              style="width: 100%"
                            /><br />
                            <img src="" id="imgView1" alt="" class="clr" style="height: 100px" />
                    
                            <div class="vald-info" id="info"></div>
                            <h5 class="error_form text-danger" id="image1_error_message"></h5>
                            <div style="display: flex">
                              <div
                                id="image-box1"
                                class="clr image-container"
                                style="height: 300px; width: 20%"
                              ></div>
                              <button
                                type="button"
                                class="btn btn-outline-info"
                                id="crop-btn1"
                                style="
                                  margin-top: 10px;
                                  display: none;
                                  width: 50%;
                                  margin: 20rem 0rem 0rem 0rem;
                                "
                              >
                                Crop
                              </button>
                            </div>
                          </div>
                    
                          <div class="">
                            <label for="productimage" class=""> Image </label>
                            <input
                              type="file"
                              id="id_image2"
                              required
                              name="image2"
                              accept="image/*"
                              class="form-control"
                              onchange="viewImage2(event)"
                              style="width: 100%"
                            /><br />
                            <img src="" id="imgView2" class="clr" alt="" style="height: 100px" />
                    
                            <div class="vald-info" id="info"></div>
                            <h5 class="error_form text-danger" id="image2_error_message"></h5>
                            <div id="image2container" style="display: flex">
                              <div
                                id="image-box2"
                                class="image-container clr"
                                style="height: 300px; width: 20%"
                              ></div>
                              <button
                                type="button"
                                class="btn btn-outline-info"
                                id="crop-btn2"
                                style="
                                  margin-top: 10px;
                                  display: none;
                                  width: 50%;
                                  margin: 20rem 0rem 0rem 0rem;
                                "
                              >
                                Crop
                              </button>
                            </div>
                          </div>
                    
                          <div class="">
                            <label for="productimage" class=""> Image </label>
                    
                            <input
                              type="file"
                              required
                              id="id_image3"
                              name="image3"
                              accept="image/*"
                              class="form-control"
                              onchange="viewImage3(event)"
                              style="width: 100%"
                            /><br />
                            <img src="" id="imgView3" class="clr" alt="" style="height: 100px" />
                    
                            <div class="vald-info" id="info"></div>
                            <h5 class="error_form text-danger" id="image3_error_message"></h5>
                            <div style="display: flex">
                              <div
                                id="image-box3"
                                class="image-container clr"
                                style="height: 300px; width: 20%"
                              ></div>
                              <button
                                type="button"
                                class="btn btn-outline-info"
                                id="crop-btn3"
                                style="
                                  margin-top: 2px;
                                  display: none;
                                  width: 50%;
                                  margin: 20rem 0rem 0rem 0rem;
                                "
                              >
                                Crop
                              </button>
                            </div>
                          </div>
                    
                        </div>
                  </div>
                  
              </div>
              
              </div>
              <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block text-uppercase">Add Product Now</button>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {%endblock%}

templates/store_admin/get-product.html
{%extends 'store_admin/admin_base.html'%}
{%load static%}
{%block content%}
    <div class="container mt-5">
      <div class="row tm-content-row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 tm-block-col">
          <div class="tm-bg-primary-dark tm-block tm-block-products">
            <div class="tm-product-table-container">
              <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                  <tr>
                    <th scope="col">&nbsp;</th>
                    <th scope="col">ID</th>
                    <th scope="col">PRODUCT NAME</th>
                    <th scope="col">UNIT SOLD</th>
                    <th scope="col">IN STOCK</th>
                    <th scope="col">CATEGORY</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">&nbsp;</th>
                  </tr>
                </thead>
                <tbody>
                  
                  <form action="{% url 'get_product' %}" method="post">{% csrf_token %} 
                    {%for product in products%}
                  <tr>
                    <th scope="row"></th>
                    <td class="tm-product-name">{{product.id}}</td>
                    <td class="tm-product-name" name = 'product_name'>{{product.name}}</td>
                    <td></td>
                    <td>{{product.stock}}</td>
                    <td>{{product.category}}</td>
                    <td> <button class="btn btn-primary btn-block text-uppercase" type="submit" name="product_id" value="{{product.id}}"> Edit Product </button></td>     
                  </tr>
                    {%endfor%}
                  </form> 
                </tbody>
              </table>
            </div>         
          </div>   
        </div>     
      </div>        
    </div>        
  </div>          
</div>
{%endblock%}